services:
  - type: web
    name: anthem-school-website
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: PHP_INI_SCAN_DIR
        value: /usr/local/etc/php/conf.d
    healthCheckPath: /index.php
    autoDeploy: true

